server:
  port: 8081

spring:
  application:
    name: PARSING-SERVICE
  profiles:
    active: language

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
