server:
  port: 8082

spring:
  application:
    name: TELEGRAM-SERVICE
  profiles:
    active: language

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

bot:
  name: ${env.BOT_NAME}
  token: ${env.BOT_TOKEN}
